### ISSUE TITLE
Android 9 and 10 support

### ISSUE THREAD

**Issue by Lucchetto** [HokoFly/HokoBlurDrawable#2]
Hi, on Android 9 and 10 callDrawGLFunction2 is no longer available, can you fix it. Thank you !

**Comment by AnthonyKoueik** [comment]
Hello , 
Kindly we need your support on this

**Comment by HokoFly** [comment]
callDrawGLFunction2 is an api in the blacklist now.  You can try to use `FreeReflection` to hack like demo 24bbc6c1f48efb5386e1801afc7e8a0597ff0b25
