### ISSUE TITLE
使用中出现卡顿现象，模糊的图片是已经滑走的背景图；demo 中无法复现。

### ISSUE THREAD

**Issue by nightjerry** [HokoFly/HokoBlurDrawable#7]
调试源码，发现在 DrawFunctor postEventFromNative 中返回的 GLInfo，执行 onDraw 方法时， mParentGLInfo.contains(info) 返回 true， 执行了 isChildRedraw = true。
打印 mParentGLInfo 和 info 的值分别为：

info = GLInfo{clipLeft=1185, clipTop=1200, clipRight=3047, clipBottom=1380, viewportWidth=3047, viewportHeight=1440, transform=[1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1200.0, 0.0, 1.0], isLayer=false}

mParentInfo = GLInfo{clipLeft=1, clipTop=1200, clipRight=3047, clipBottom=1380, viewportWidth=3047, viewportHeight=1440, transform=[1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1200.0, 0.0, 1.0], isLayer=false}

我注销掉 DrawFunctor.onDraw() 中的if/ else 判断， 直接执行 else 内的代码块，暂时规避问题；
还未跟进 c++ 代码；
大佬有时间关注下。

**Comment by HokoFly** [comment]
测试用例描述的更详细一些吧，或者具体的布局状态

**Comment by HokoFly** [comment]
这里对脏区域父区域做了一刀切模糊处理，会影响性能 
545d6767380bf6e4788ead906451a3795f879c5b 增加相关配置，默认关闭该特性，你不需要做任何处理了
